package com.github.nechaevv.isomorphic.dom

object tags {
  val a      = Tag("a")
  val button = Tag("button")
  val div    = Tag("div")
  val footer = Tag("footer")
  val form   = Tag("form")
  val h1     = Tag("h1")
  val h2     = Tag("h2")
  val header = Tag("header")
  val img    = Tag("img")
  val input  = Tag("input")
  val label  = Tag("label")
  val li     = Tag("li")
  val option = Tag("option")
  val p      = Tag("p")
  val section= Tag("section")
  val select = Tag("select")
  val slot   = Tag("slot")
  val span   = Tag("span")
  val table  = Tag("table")
  val tbody  = Tag("tbody")
  val td     = Tag("td")
  val th     = Tag("th")
  val thead  = Tag("thead")
  val tr     = Tag("tr")
  val ul     = Tag("ul")
}