package com.github.nechaevv.isomorphic.dom

object tags {
  val a      = TagNode("a")
  val button = TagNode("button")
  val div    = TagNode("div")
  val footer = TagNode("footer")
  val form   = TagNode("form")
  val h1     = TagNode("h1")
  val h2     = TagNode("h2")
  val header = TagNode("header")
  val img    = TagNode("img")
  val input  = TagNode("input")
  val label  = TagNode("label")
  val li     = TagNode("li")
  val option = TagNode("option")
  val p      = TagNode("p")
  val section= TagNode("section")
  val select = TagNode("select")
  val slot   = TagNode("slot")
  val span   = TagNode("span")
  val table  = TagNode("table")
  val tbody  = TagNode("tbody")
  val td     = TagNode("td")
  val th     = TagNode("th")
  val thead  = TagNode("thead")
  val tr     = TagNode("tr")
  val ul     = TagNode("ul")
}