package com.github.nechaevv.isomorphic.vdom

object tags {
  val a      = ElementVNode("a")
  val button = ElementVNode("button")
  val div    = ElementVNode("div")
  val footer = ElementVNode("footer")
  val form   = ElementVNode("form")
  val h1     = ElementVNode("h1")
  val h2     = ElementVNode("h2")
  val h3     = ElementVNode("h3")
  val h4     = ElementVNode("h4")
  val header = ElementVNode("header")
  val img    = ElementVNode("img")
  val input  = ElementVNode("input")
  val label  = ElementVNode("label")
  val li     = ElementVNode("li")
  val nav    = ElementVNode("nav")
  val option = ElementVNode("option")
  val p      = ElementVNode("p")
  val section= ElementVNode("section")
  val select = ElementVNode("select")
  val slot   = ElementVNode("slot")
  val span   = ElementVNode("span")
  val table  = ElementVNode("table")
  val tbody  = ElementVNode("tbody")
  val td     = ElementVNode("td")
  val th     = ElementVNode("th")
  val thead  = ElementVNode("thead")
  val tr     = ElementVNode("tr")
  val ul     = ElementVNode("ul")
}
